version: '3.8'
services:
  chocolate-engine:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=file:/usr/src/app/data/dev.db
    volumes:
      - ./data:/usr/src/app/data # This keeps your SQLite DB safe even if the container restarts